### ISSUE TITLE
`make dist` fails with old version of gb installed

### ISSUE THREAD

**Issue by robbles** [skizzehq/skizze#163]
I have an old version of gb on my machine, and it looks like the Makefile is picking that up instead of the one installed in the `vendor/bin` directory.

It fails with the following error:

```
ERROR unknown command "vendor"
Usage:
  gb plugin [flags] [package] - run a plugin
  gb test [flags] [package] - test a package
  gb build [flags] [package] - build a package

Flags:
  -R string
    	set the project root (default "/Users/rob/go/src/github.com/skizzehq/skizze")
  -goroot string
    	override GOROOT (default "/usr/local/Cellar/go/1.5.1/libexec")
  -q	suppress log messages below ERROR level
  -v	enable log levels below INFO level
Makefile:24: recipe for target 'vendor' failed
make: *** [vendor] Error 1
```

I think the fix for this might be as simple as setting PATH at the top of the Makefile, to ensure that the installed version of gb is used?

**Comment by bahlo** [comment]
We can't use `vendor/bin/gb` since the folder is empty on first clone (apart from the manifest).

What about changing the `build-dep` step (that get's called on `make dist`) to the following:

```Makefile
build-dep:
	@go get -u github.com/constabulary/gb/...
```

The `-u`-flag tells go to download the package, even if installed. Since it compares hashes before actually compiling, it's not really slowing down the build.

Or maybe it'd make sense to use something like [gopkg.in](http://gopkg.in) instead of GitHub to prevent breaking changes like these in the future? We wouldn't need `-u` then.

**Comment by robbles** [comment]
@bahlo I did try that, actually. That doesn't work, because the GOPATH is modified at the start of the makefile. So it does update gb, but only the one in the vendor directory, not my system-installed one.

Are you sure you can't use the binary in vendor? If you prefixed the PATH with that bin directory, it would use it when it's there. The first task that gets called by the Makefile will install it anyways.

**Comment by robbles** [comment]
I read your comment again, and I think you're talking about how to prevent the use of a new, incompatible version of gb. That's not an issue here - I just had a really old version of gb that didn't support the `vendor` command, and the Makefile doesn't use the version it installs by default. If it used the version of gb that gets installed in `build-dep` I think this would be fine.

**Comment by bahlo** [comment]
@robbles: I'm not sure if `go` would actually update your version of `gb` on `go get` without `-u`. If it doesn't, this is another problem which we should address since we don't know when `gb` will get the next breaking changes.

But you're right, it'd be best to just expand the PATH to `vendor/bin` or just call `./vendor/bin/gb` instead of just `gb`.

**Comment by bahlo** [comment]
We then have three possibilities:

1. Set the path before the call: `PATH=$(PATH):$(CURDIR)/vendor/bin gb …`,
2. call the binary directly: `$(CURDIR)/vendor/bin/gb …`, 
3. or set a variable for the path to the binary (`GB=$(CURDIR)/vendor/bin/gb`) and use that: `$(GB) …`

In my opinion, option three is the best here. What do you think?

**Comment by robbles** [comment]
@bahlo (3) sounds like a good fix to me.
